"""schema initial

Revision ID: 9c987320cf76
Revises: 
Create Date: 2026-08-15 04:46:12.684737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c987320cf76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlight',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_highlight_code'), 'highlight', ['code'], unique=True)
    op.create_index(op.f('ix_highlight_deleted_at'), 'highlight', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_highlight_id'), 'highlight', ['id'], unique=False)
    op.create_table('inclusion',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inclusion_code'), 'inclusion', ['code'], unique=True)
    op.create_index(op.f('ix_inclusion_deleted_at'), 'inclusion', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_inclusion_id'), 'inclusion', ['id'], unique=False)
    op.create_table('media',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('IMAGE', 'VIDEO', 'DOCUMENT', name='mediakind'), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('blurhash', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('dominant_color', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('photographer', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('taken_at', sa.Date(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('folder', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_deleted_at'), 'media', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_media_folder'), 'media', ['folder'], unique=False)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_index(op.f('ix_media_kind'), 'media', ['kind'], unique=False)
    op.create_table('packing_item',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_item_code'), 'packing_item', ['code'], unique=True)
    op.create_index(op.f('ix_packing_item_deleted_at'), 'packing_item', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_packing_item_id'), 'packing_item', ['id'], unique=False)
    op.create_table('redirect',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('to_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redirect_from_path'), 'redirect', ['from_path'], unique=True)
    op.create_index(op.f('ix_redirect_id'), 'redirect', ['id'], unique=False)
    op.create_index(op.f('ix_redirect_is_active'), 'redirect', ['is_active'], unique=False)
    op.create_table('setting',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_group'), 'setting', ['group'], unique=False)
    op.create_index(op.f('ix_setting_id'), 'setting', ['id'], unique=False)
    op.create_index(op.f('ix_setting_key'), 'setting', ['key'], unique=True)
    op.create_table('admin_user',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'EDITOR', 'MODERATOR', 'VIEWER', name='adminrole'), nullable=False),
    sa.Column('preferred_locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_media_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['avatar_media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_deleted_at'), 'admin_user', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_admin_user_email'), 'admin_user', ['email'], unique=True)
    op.create_index(op.f('ix_admin_user_id'), 'admin_user', ['id'], unique=False)
    op.create_index(op.f('ix_admin_user_is_active'), 'admin_user', ['is_active'], unique=False)
    op.create_index(op.f('ix_admin_user_role'), 'admin_user', ['role'], unique=False)
    op.create_table('blog_category',
    sa.Column('is_indexable', sa.Boolean(), nullable=False),
    sa.Column('canonical_override', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('sitemap_priority', sa.Float(), nullable=False),
    sa.Column('sitemap_changefreq', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=True),
    sa.Column('cover_media_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_category_code'), 'blog_category', ['code'], unique=True)
    op.create_index(op.f('ix_blog_category_deleted_at'), 'blog_category', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_blog_category_id'), 'blog_category', ['id'], unique=False)
    op.create_index(op.f('ix_blog_category_is_published'), 'blog_category', ['is_published'], unique=False)
    op.create_index(op.f('ix_blog_category_published_at'), 'blog_category', ['published_at'], unique=False)
    op.create_index(op.f('ix_blog_category_slug'), 'blog_category', ['slug'], unique=True)
    op.create_index(op.f('ix_blog_category_sort_order'), 'blog_category', ['sort_order'], unique=False)
    op.create_table('destination',
    sa.Column('is_indexable', sa.Boolean(), nullable=False),
    sa.Column('canonical_override', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('sitemap_priority', sa.Float(), nullable=False),
    sa.Column('sitemap_changefreq', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('cover_media_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destination_code'), 'destination', ['code'], unique=True)
    op.create_index(op.f('ix_destination_deleted_at'), 'destination', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_destination_id'), 'destination', ['id'], unique=False)
    op.create_index(op.f('ix_destination_is_published'), 'destination', ['is_published'], unique=False)
    op.create_index(op.f('ix_destination_parent_id'), 'destination', ['parent_id'], unique=False)
    op.create_index(op.f('ix_destination_published_at'), 'destination', ['published_at'], unique=False)
    op.create_index(op.f('ix_destination_slug'), 'destination', ['slug'], unique=True)
    op.create_index(op.f('ix_destination_sort_order'), 'destination', ['sort_order'], unique=False)
    op.create_table('gallery',
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cover_media_id', sa.Uuid(), nullable=True),
    sa.Column('is_indexable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_deleted_at'), 'gallery', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_gallery_id'), 'gallery', ['id'], unique=False)
    op.create_index(op.f('ix_gallery_is_published'), 'gallery', ['is_published'], unique=False)
    op.create_index(op.f('ix_gallery_published_at'), 'gallery', ['published_at'], unique=False)
    op.create_index(op.f('ix_gallery_slug'), 'gallery', ['slug'], unique=True)
    op.create_index(op.f('ix_gallery_sort_order'), 'gallery', ['sort_order'], unique=False)
    op.create_table('highlight_translation',
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('highlight_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlight.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('highlight_id', 'locale', name='uq_highlight_translation')
    )
    op.create_index(op.f('ix_highlight_translation_highlight_id'), 'highlight_translation', ['highlight_id'], unique=False)
    op.create_index(op.f('ix_highlight_translation_id'), 'highlight_translation', ['id'], unique=False)
    op.create_index(op.f('ix_highlight_translation_locale'), 'highlight_translation', ['locale'], unique=False)
    op.create_table('inclusion_translation',
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inclusion_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.ForeignKeyConstraint(['inclusion_id'], ['inclusion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inclusion_id', 'locale', name='uq_inclusion_translation')
    )
    op.create_index(op.f('ix_inclusion_translation_id'), 'inclusion_translation', ['id'], unique=False)
    op.create_index(op.f('ix_inclusion_translation_inclusion_id'), 'inclusion_translation', ['inclusion_id'], unique=False)
    op.create_index(op.f('ix_inclusion_translation_locale'), 'inclusion_translation', ['locale'], unique=False)
    op.create_table('media_translation',
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'locale', name='uq_media_translation')
    )
    op.create_index(op.f('ix_media_translation_id'), 'media_translation', ['id'], unique=False)
    op.create_index(op.f('ix_media_translation_locale'), 'media_translation', ['locale'], unique=False)
    op.create_index(op.f('ix_media_translation_media_id'), 'media_translation', ['media_id'], unique=False)
    op.create_table('packing_item_translation',
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('packing_item_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.ForeignKeyConstraint(['packing_item_id'], ['packing_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('packing_item_id', 'locale', name='uq_packing_item_translation')
    )
    op.create_index(op.f('ix_packing_item_translation_id'), 'packing_item_translation', ['id'], unique=False)
    op.create_index(op.f('ix_packing_item_translation_locale'), 'packing_item_translation', ['locale'], unique=False)
    op.create_index(op.f('ix_packing_item_translation_packing_item_id'), 'packing_item_translation', ['packing_item_id'], unique=False)
    op.create_table('page',
    sa.Column('is_indexable', sa.Boolean(), nullable=False),
    sa.Column('canonical_override', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('sitemap_priority', sa.Float(), nullable=False),
    sa.Column('sitemap_changefreq', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('hero_media_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['hero_media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_deleted_at'), 'page', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_page_id'), 'page', ['id'], unique=False)
    op.create_index(op.f('ix_page_is_published'), 'page', ['is_published'], unique=False)
    op.create_index(op.f('ix_page_published_at'), 'page', ['published_at'], unique=False)
    op.create_index(op.f('ix_page_slug'), 'page', ['slug'], unique=True)
    op.create_index(op.f('ix_page_sort_order'), 'page', ['sort_order'], unique=False)
    op.create_index(op.f('ix_page_status'), 'page', ['status'], unique=False)
    op.create_table('setting_translation',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('setting_id', sa.Uuid(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_id', 'locale', name='uq_setting_translation')
    )
    op.create_index(op.f('ix_setting_translation_id'), 'setting_translation', ['id'], unique=False)
    op.create_index(op.f('ix_setting_translation_locale'), 'setting_translation', ['locale'], unique=False)
    op.create_index(op.f('ix_setting_translation_setting_id'), 'setting_translation', ['setting_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'PUBLISH', 'UNPUBLISH', 'STATUS_CHANGE', 'LOGIN', 'LOGIN_FAILED', name='auditaction'), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_label', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('changes_before', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('changes_after', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('author',
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('avatar_media_id', sa.Uuid(), nullable=True),
    sa.Column('admin_user_id', sa.Uuid(), nullable=True),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('facebook_url', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('instagram_url', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_user.id'], ),
    sa.ForeignKeyConstraint(['avatar_media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_deleted_at'), 'author', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_author_id'), 'author', ['id'], unique=False)
    op.create_index(op.f('ix_author_slug'), 'author', ['slug'], unique=True)
    op.create_table('blog_category_translation',
    sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=70), nullable=True),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=180), nullable=True),
    sa.Column('og_title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('og_description', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=800), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['blog_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'locale', name='uq_blog_category_translation')
    )
    op.create_index(op.f('ix_blog_category_translation_category_id'), 'blog_category_translation', ['category_id'], unique=False)
    op.create_index(op.f('ix_blog_category_translation_id'), 'blog_category_translation', ['id'], unique=False)
    op.create_index(op.f('ix_blog_category_translation_locale'), 'blog_category_translation', ['locale'], unique=False)
    op.create_table('contact_message',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handled_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('spam_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['handled_by'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_message_deleted_at'), 'contact_message', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_contact_message_email'), 'contact_message', ['email'], unique=False)
    op.create_index(op.f('ix_contact_message_id'), 'contact_message', ['id'], unique=False)
    op.create_index(op.f('ix_contact_message_is_archived'), 'contact_message', ['is_archived'], unique=False)
    op.create_index(op.f('ix_contact_message_is_read'), 'contact_message', ['is_read'], unique=False)
    op.create_table('destination_translation',
    sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=70), nullable=True),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=180), nullable=True),
    sa.Column('og_title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('og_description', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id', 'locale', name='uq_destination_translation')
    )
    op.create_index(op.f('ix_destination_translation_destination_id'), 'destination_translation', ['destination_id'], unique=False)
    op.create_index(op.f('ix_destination_translation_id'), 'destination_translation', ['id'], unique=False)
    op.create_index(op.f('ix_destination_translation_locale'), 'destination_translation', ['locale'], unique=False)
    op.create_table('gallery_media',
    sa.Column('gallery_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gallery_id', 'media_id')
    )
    op.create_table('gallery_translation',
    sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=70), nullable=True),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=180), nullable=True),
    sa.Column('og_title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('og_description', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gallery_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gallery_id', 'locale', name='uq_gallery_translation')
    )
    op.create_index(op.f('ix_gallery_translation_gallery_id'), 'gallery_translation', ['gallery_id'], unique=False)
    op.create_index(op.f('ix_gallery_translation_id'), 'gallery_translation', ['id'], unique=False)
    op.create_index(op.f('ix_gallery_translation_locale'), 'gallery_translation', ['locale'], unique=False)
    op.create_table('page_section',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('section_type', sa.Enum('HERO', 'RICH_TEXT', 'VALUES', 'STORY', 'PILLARS', 'STATS', 'FAQ', 'GALLERY', 'CTA', 'TESTIMONIALS', 'PRODUCT_GRID', name='pagesectiontype'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('anchor', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('gallery_id', sa.Uuid(), nullable=True),
    sa.Column('background_variant', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('cta_url', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_section_id'), 'page_section', ['id'], unique=False)
    op.create_index(op.f('ix_page_section_page_id'), 'page_section', ['page_id'], unique=False)
    op.create_index(op.f('ix_page_section_section_type'), 'page_section', ['section_type'], unique=False)
    op.create_index(op.f('ix_page_section_sort_order'), 'page_section', ['sort_order'], unique=False)
    op.create_table('page_translation',
    sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=70), nullable=True),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=180), nullable=True),
    sa.Column('og_title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('og_description', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('eyebrow', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('intro', sqlmodel.sql.sqltypes.AutoString(length=800), nullable=True),
    sa.Column('breadcrumb_label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'locale', name='uq_page_translation')
    )
    op.create_index(op.f('ix_page_translation_id'), 'page_translation', ['id'], unique=False)
    op.create_index(op.f('ix_page_translation_is_published'), 'page_translation', ['is_published'], unique=False)
    op.create_index(op.f('ix_page_translation_locale'), 'page_translation', ['locale'], unique=False)
    op.create_index(op.f('ix_page_translation_page_id'), 'page_translation', ['page_id'], unique=False)
    op.create_table('product',
    sa.Column('is_indexable', sa.Boolean(), nullable=False),
    sa.Column('canonical_override', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('sitemap_priority', sa.Float(), nullable=False),
    sa.Column('sitemap_changefreq', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_type', sa.Enum('CIRCUIT', 'EXCURSION', name='producttype'), nullable=False),
    sa.Column('product_format', sa.Enum('FULL_DAY', 'HALF_DAY', 'EVENING', 'MULTI_DAY', name='productformat'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('duration_nights', sa.Integer(), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('return_time', sa.Time(), nullable=True),
    sa.Column('travel_minutes', sa.Integer(), nullable=True),
    sa.Column('transport', sa.Enum('BOAT', 'VEHICLE', 'PIROGUE', 'MIXED', 'WALKING', name='transportmode'), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MODERATE', 'SPORTY', name='difficultylevel'), nullable=False),
    sa.Column('group_min', sa.Integer(), nullable=False),
    sa.Column('group_max', sa.Integer(), nullable=False),
    sa.Column('hotel_pickup', sa.Boolean(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('price_from', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('deposit_percent', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Uuid(), nullable=True),
    sa.Column('cover_media_id', sa.Uuid(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('rating_average', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_deleted_at'), 'product', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_product_destination_id'), 'product', ['destination_id'], unique=False)
    op.create_index(op.f('ix_product_difficulty'), 'product', ['difficulty'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_is_featured'), 'product', ['is_featured'], unique=False)
    op.create_index(op.f('ix_product_is_published'), 'product', ['is_published'], unique=False)
    op.create_index(op.f('ix_product_product_format'), 'product', ['product_format'], unique=False)
    op.create_index(op.f('ix_product_product_type'), 'product', ['product_type'], unique=False)
    op.create_index(op.f('ix_product_published_at'), 'product', ['published_at'], unique=False)
    op.create_index(op.f('ix_product_slug'), 'product', ['slug'], unique=True)
    op.create_index(op.f('ix_product_sort_order'), 'product', ['sort_order'], unique=False)
    op.create_index(op.f('ix_product_status'), 'product', ['status'], unique=False)
    op.create_table('revalidation_log',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revalidation_log_id'), 'revalidation_log', ['id'], unique=False)
    op.create_index(op.f('ix_revalidation_log_is_success'), 'revalidation_log', ['is_success'], unique=False)
    op.create_index(op.f('ix_revalidation_log_tag'), 'revalidation_log', ['tag'], unique=False)
    op.create_table('slug_history',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('old_slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('new_slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slug_history_entity_id'), 'slug_history', ['entity_id'], unique=False)
    op.create_index(op.f('ix_slug_history_entity_type'), 'slug_history', ['entity_type'], unique=False)
    op.create_index(op.f('ix_slug_history_id'), 'slug_history', ['id'], unique=False)
    op.create_index(op.f('ix_slug_history_old_slug'), 'slug_history', ['old_slug'], unique=False)
    op.create_table('author_translation',
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('role_label', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=1500), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'locale', name='uq_author_translation')
    )
    op.create_index(op.f('ix_author_translation_author_id'), 'author_translation', ['author_id'], unique=False)
    op.create_index(op.f('ix_author_translation_id'), 'author_translation', ['id'], unique=False)
    op.create_index(op.f('ix_author_translation_locale'), 'author_translation', ['locale'], unique=False)
    op.create_table('blog_post',
    sa.Column('is_indexable', sa.Boolean(), nullable=False),
    sa.Column('canonical_override', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('sitemap_priority', sa.Float(), nullable=False),
    sa.Column('sitemap_changefreq', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('cover_media_id', sa.Uuid(), nullable=True),
    sa.Column('content_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reading_minutes', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['blog_category.id'], ),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_post_author_id'), 'blog_post', ['author_id'], unique=False)
    op.create_index(op.f('ix_blog_post_category_id'), 'blog_post', ['category_id'], unique=False)
    op.create_index(op.f('ix_blog_post_content_updated_at'), 'blog_post', ['content_updated_at'], unique=False)
    op.create_index(op.f('ix_blog_post_deleted_at'), 'blog_post', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_blog_post_id'), 'blog_post', ['id'], unique=False)
    op.create_index(op.f('ix_blog_post_is_featured'), 'blog_post', ['is_featured'], unique=False)
    op.create_index(op.f('ix_blog_post_is_published'), 'blog_post', ['is_published'], unique=False)
    op.create_index(op.f('ix_blog_post_published_at'), 'blog_post', ['published_at'], unique=False)
    op.create_index(op.f('ix_blog_post_slug'), 'blog_post', ['slug'], unique=True)
    op.create_index(op.f('ix_blog_post_sort_order'), 'blog_post', ['sort_order'], unique=False)
    op.create_index(op.f('ix_blog_post_status'), 'blog_post', ['status'], unique=False)
    op.create_table('booking',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUOTED', 'PENDING_PAYMENT', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('product_slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('product_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('product_type', sa.Enum('CIRCUIT', 'EXCURSION', name='producttype'), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('customer_phone', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('customer_country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('preferred_locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('hotel_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('alternative_date', sa.Date(), nullable=True),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('customer_message', sqlmodel.sql.sqltypes.AutoString(length=3000), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deposit_paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('balance_paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('internal_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('first_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('WEBSITE', 'WHATSAPP', 'PHONE', 'EMAIL', 'PARTNER', 'WALK_IN', name='bookingsource'), nullable=False),
    sa.Column('utm_source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('utm_medium', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('utm_campaign', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('referrer_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('landing_page', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('submitted_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['admin_user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_assigned_to'), 'booking', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_booking_customer_email'), 'booking', ['customer_email'], unique=False)
    op.create_index(op.f('ix_booking_deleted_at'), 'booking', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_booking_id'), 'booking', ['id'], unique=False)
    op.create_index(op.f('ix_booking_product_id'), 'booking', ['product_id'], unique=False)
    op.create_index(op.f('ix_booking_reference'), 'booking', ['reference'], unique=True)
    op.create_index(op.f('ix_booking_requested_date'), 'booking', ['requested_date'], unique=False)
    op.create_index(op.f('ix_booking_source'), 'booking', ['source'], unique=False)
    op.create_index(op.f('ix_booking_status'), 'booking', ['status'], unique=False)
    op.create_table('page_section_item',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('numeric_value', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('link_url', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['page_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_section_item_id'), 'page_section_item', ['id'], unique=False)
    op.create_index(op.f('ix_page_section_item_section_id'), 'page_section_item', ['section_id'], unique=False)
    op.create_table('page_section_translation',
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('eyebrow', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cta_label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['page_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'locale', name='uq_page_section_translation')
    )
    op.create_index(op.f('ix_page_section_translation_id'), 'page_section_translation', ['id'], unique=False)
    op.create_index(op.f('ix_page_section_translation_locale'), 'page_section_translation', ['locale'], unique=False)
    op.create_index(op.f('ix_page_section_translation_section_id'), 'page_section_translation', ['section_id'], unique=False)
    op.create_table('product_departure_month',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'month')
    )
    op.create_table('product_faq',
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_faq_id'), 'product_faq', ['id'], unique=False)
    op.create_index(op.f('ix_product_faq_locale'), 'product_faq', ['locale'], unique=False)
    op.create_index(op.f('ix_product_faq_product_id'), 'product_faq', ['product_id'], unique=False)
    op.create_table('product_highlight',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('highlight_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlight.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'highlight_id')
    )
    op.create_table('product_inclusion',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('inclusion_id', sa.Uuid(), nullable=False),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inclusion_id'], ['inclusion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'inclusion_id')
    )
    op.create_table('product_itinerary_item',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('time_label', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_itinerary_item_id'), 'product_itinerary_item', ['id'], unique=False)
    op.create_index(op.f('ix_product_itinerary_item_product_id'), 'product_itinerary_item', ['product_id'], unique=False)
    op.create_table('product_media',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'media_id')
    )
    op.create_table('product_packing_item',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('packing_item_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['packing_item_id'], ['packing_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'packing_item_id')
    )
    op.create_table('product_price_tier',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('label_code', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_pax', sa.Integer(), nullable=True),
    sa.Column('max_pax', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_price_tier_id'), 'product_price_tier', ['id'], unique=False)
    op.create_index(op.f('ix_product_price_tier_product_id'), 'product_price_tier', ['product_id'], unique=False)
    op.create_table('product_related',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('related_product_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'related_product_id')
    )
    op.create_table('product_translation',
    sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=70), nullable=True),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=180), nullable=True),
    sa.Column('og_title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('og_description', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('region_label', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('practical_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'locale', name='uq_product_translation')
    )
    op.create_index(op.f('ix_product_translation_id'), 'product_translation', ['id'], unique=False)
    op.create_index(op.f('ix_product_translation_locale'), 'product_translation', ['locale'], unique=False)
    op.create_index(op.f('ix_product_translation_product_id'), 'product_translation', ['product_id'], unique=False)
    op.create_table('review',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('author_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('author_country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('author_media_id', sa.Uuid(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SPAM', name='reviewstatus'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('booking_reference', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderated_by', sa.Uuid(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('admin_reply', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('admin_replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('spam_score', sa.Float(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['moderated_by'], ['admin_user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_author_email'), 'review', ['author_email'], unique=False)
    op.create_index(op.f('ix_review_deleted_at'), 'review', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    op.create_index(op.f('ix_review_is_featured'), 'review', ['is_featured'], unique=False)
    op.create_index(op.f('ix_review_is_verified'), 'review', ['is_verified'], unique=False)
    op.create_index(op.f('ix_review_locale'), 'review', ['locale'], unique=False)
    op.create_index(op.f('ix_review_product_id'), 'review', ['product_id'], unique=False)
    op.create_index(op.f('ix_review_rating'), 'review', ['rating'], unique=False)
    op.create_index(op.f('ix_review_status'), 'review', ['status'], unique=False)
    op.create_table('blog_post_product',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'product_id')
    )
    op.create_table('blog_post_related',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('related_post_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'related_post_id')
    )
    op.create_table('blog_post_translation',
    sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(length=70), nullable=True),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(length=180), nullable=True),
    sa.Column('og_title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('og_description', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'locale', name='uq_blog_post_translation')
    )
    op.create_index(op.f('ix_blog_post_translation_id'), 'blog_post_translation', ['id'], unique=False)
    op.create_index(op.f('ix_blog_post_translation_is_published'), 'blog_post_translation', ['is_published'], unique=False)
    op.create_index(op.f('ix_blog_post_translation_locale'), 'blog_post_translation', ['locale'], unique=False)
    op.create_index(op.f('ix_blog_post_translation_post_id'), 'blog_post_translation', ['post_id'], unique=False)
    op.create_table('booking_status_history',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('NEW', 'CONTACTED', 'QUOTED', 'PENDING_PAYMENT', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='bookingstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('NEW', 'CONTACTED', 'QUOTED', 'PENDING_PAYMENT', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('is_automatic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_status_history_booking_id'), 'booking_status_history', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_status_history_id'), 'booking_status_history', ['id'], unique=False)
    op.create_table('page_section_item_translation',
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['page_section_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'locale', name='uq_page_section_item_translation')
    )
    op.create_index(op.f('ix_page_section_item_translation_id'), 'page_section_item_translation', ['id'], unique=False)
    op.create_index(op.f('ix_page_section_item_translation_item_id'), 'page_section_item_translation', ['item_id'], unique=False)
    op.create_index(op.f('ix_page_section_item_translation_locale'), 'page_section_item_translation', ['locale'], unique=False)
    op.create_table('product_itinerary_translation',
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['product_itinerary_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'locale', name='uq_product_itinerary_translation')
    )
    op.create_index(op.f('ix_product_itinerary_translation_id'), 'product_itinerary_translation', ['id'], unique=False)
    op.create_index(op.f('ix_product_itinerary_translation_item_id'), 'product_itinerary_translation', ['item_id'], unique=False)
    op.create_index(op.f('ix_product_itinerary_translation_locale'), 'product_itinerary_translation', ['locale'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_itinerary_translation_locale'), table_name='product_itinerary_translation')
    op.drop_index(op.f('ix_product_itinerary_translation_item_id'), table_name='product_itinerary_translation')
    op.drop_index(op.f('ix_product_itinerary_translation_id'), table_name='product_itinerary_translation')
    op.drop_table('product_itinerary_translation')
    op.drop_index(op.f('ix_page_section_item_translation_locale'), table_name='page_section_item_translation')
    op.drop_index(op.f('ix_page_section_item_translation_item_id'), table_name='page_section_item_translation')
    op.drop_index(op.f('ix_page_section_item_translation_id'), table_name='page_section_item_translation')
    op.drop_table('page_section_item_translation')
    op.drop_index(op.f('ix_booking_status_history_id'), table_name='booking_status_history')
    op.drop_index(op.f('ix_booking_status_history_booking_id'), table_name='booking_status_history')
    op.drop_table('booking_status_history')
    op.drop_index(op.f('ix_blog_post_translation_post_id'), table_name='blog_post_translation')
    op.drop_index(op.f('ix_blog_post_translation_locale'), table_name='blog_post_translation')
    op.drop_index(op.f('ix_blog_post_translation_is_published'), table_name='blog_post_translation')
    op.drop_index(op.f('ix_blog_post_translation_id'), table_name='blog_post_translation')
    op.drop_table('blog_post_translation')
    op.drop_table('blog_post_related')
    op.drop_table('blog_post_product')
    op.drop_index(op.f('ix_review_status'), table_name='review')
    op.drop_index(op.f('ix_review_rating'), table_name='review')
    op.drop_index(op.f('ix_review_product_id'), table_name='review')
    op.drop_index(op.f('ix_review_locale'), table_name='review')
    op.drop_index(op.f('ix_review_is_verified'), table_name='review')
    op.drop_index(op.f('ix_review_is_featured'), table_name='review')
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.drop_index(op.f('ix_review_deleted_at'), table_name='review')
    op.drop_index(op.f('ix_review_author_email'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_product_translation_product_id'), table_name='product_translation')
    op.drop_index(op.f('ix_product_translation_locale'), table_name='product_translation')
    op.drop_index(op.f('ix_product_translation_id'), table_name='product_translation')
    op.drop_table('product_translation')
    op.drop_table('product_related')
    op.drop_index(op.f('ix_product_price_tier_product_id'), table_name='product_price_tier')
    op.drop_index(op.f('ix_product_price_tier_id'), table_name='product_price_tier')
    op.drop_table('product_price_tier')
    op.drop_table('product_packing_item')
    op.drop_table('product_media')
    op.drop_index(op.f('ix_product_itinerary_item_product_id'), table_name='product_itinerary_item')
    op.drop_index(op.f('ix_product_itinerary_item_id'), table_name='product_itinerary_item')
    op.drop_table('product_itinerary_item')
    op.drop_table('product_inclusion')
    op.drop_table('product_highlight')
    op.drop_index(op.f('ix_product_faq_product_id'), table_name='product_faq')
    op.drop_index(op.f('ix_product_faq_locale'), table_name='product_faq')
    op.drop_index(op.f('ix_product_faq_id'), table_name='product_faq')
    op.drop_table('product_faq')
    op.drop_table('product_departure_month')
    op.drop_index(op.f('ix_page_section_translation_section_id'), table_name='page_section_translation')
    op.drop_index(op.f('ix_page_section_translation_locale'), table_name='page_section_translation')
    op.drop_index(op.f('ix_page_section_translation_id'), table_name='page_section_translation')
    op.drop_table('page_section_translation')
    op.drop_index(op.f('ix_page_section_item_section_id'), table_name='page_section_item')
    op.drop_index(op.f('ix_page_section_item_id'), table_name='page_section_item')
    op.drop_table('page_section_item')
    op.drop_index(op.f('ix_booking_status'), table_name='booking')
    op.drop_index(op.f('ix_booking_source'), table_name='booking')
    op.drop_index(op.f('ix_booking_requested_date'), table_name='booking')
    op.drop_index(op.f('ix_booking_reference'), table_name='booking')
    op.drop_index(op.f('ix_booking_product_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_deleted_at'), table_name='booking')
    op.drop_index(op.f('ix_booking_customer_email'), table_name='booking')
    op.drop_index(op.f('ix_booking_assigned_to'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_blog_post_status'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_sort_order'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_slug'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_published_at'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_is_published'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_is_featured'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_id'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_deleted_at'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_content_updated_at'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_category_id'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_author_id'), table_name='blog_post')
    op.drop_table('blog_post')
    op.drop_index(op.f('ix_author_translation_locale'), table_name='author_translation')
    op.drop_index(op.f('ix_author_translation_id'), table_name='author_translation')
    op.drop_index(op.f('ix_author_translation_author_id'), table_name='author_translation')
    op.drop_table('author_translation')
    op.drop_index(op.f('ix_slug_history_old_slug'), table_name='slug_history')
    op.drop_index(op.f('ix_slug_history_id'), table_name='slug_history')
    op.drop_index(op.f('ix_slug_history_entity_type'), table_name='slug_history')
    op.drop_index(op.f('ix_slug_history_entity_id'), table_name='slug_history')
    op.drop_table('slug_history')
    op.drop_index(op.f('ix_revalidation_log_tag'), table_name='revalidation_log')
    op.drop_index(op.f('ix_revalidation_log_is_success'), table_name='revalidation_log')
    op.drop_index(op.f('ix_revalidation_log_id'), table_name='revalidation_log')
    op.drop_table('revalidation_log')
    op.drop_index(op.f('ix_product_status'), table_name='product')
    op.drop_index(op.f('ix_product_sort_order'), table_name='product')
    op.drop_index(op.f('ix_product_slug'), table_name='product')
    op.drop_index(op.f('ix_product_published_at'), table_name='product')
    op.drop_index(op.f('ix_product_product_type'), table_name='product')
    op.drop_index(op.f('ix_product_product_format'), table_name='product')
    op.drop_index(op.f('ix_product_is_published'), table_name='product')
    op.drop_index(op.f('ix_product_is_featured'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_difficulty'), table_name='product')
    op.drop_index(op.f('ix_product_destination_id'), table_name='product')
    op.drop_index(op.f('ix_product_deleted_at'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_page_translation_page_id'), table_name='page_translation')
    op.drop_index(op.f('ix_page_translation_locale'), table_name='page_translation')
    op.drop_index(op.f('ix_page_translation_is_published'), table_name='page_translation')
    op.drop_index(op.f('ix_page_translation_id'), table_name='page_translation')
    op.drop_table('page_translation')
    op.drop_index(op.f('ix_page_section_sort_order'), table_name='page_section')
    op.drop_index(op.f('ix_page_section_section_type'), table_name='page_section')
    op.drop_index(op.f('ix_page_section_page_id'), table_name='page_section')
    op.drop_index(op.f('ix_page_section_id'), table_name='page_section')
    op.drop_table('page_section')
    op.drop_index(op.f('ix_gallery_translation_locale'), table_name='gallery_translation')
    op.drop_index(op.f('ix_gallery_translation_id'), table_name='gallery_translation')
    op.drop_index(op.f('ix_gallery_translation_gallery_id'), table_name='gallery_translation')
    op.drop_table('gallery_translation')
    op.drop_table('gallery_media')
    op.drop_index(op.f('ix_destination_translation_locale'), table_name='destination_translation')
    op.drop_index(op.f('ix_destination_translation_id'), table_name='destination_translation')
    op.drop_index(op.f('ix_destination_translation_destination_id'), table_name='destination_translation')
    op.drop_table('destination_translation')
    op.drop_index(op.f('ix_contact_message_is_read'), table_name='contact_message')
    op.drop_index(op.f('ix_contact_message_is_archived'), table_name='contact_message')
    op.drop_index(op.f('ix_contact_message_id'), table_name='contact_message')
    op.drop_index(op.f('ix_contact_message_email'), table_name='contact_message')
    op.drop_index(op.f('ix_contact_message_deleted_at'), table_name='contact_message')
    op.drop_table('contact_message')
    op.drop_index(op.f('ix_blog_category_translation_locale'), table_name='blog_category_translation')
    op.drop_index(op.f('ix_blog_category_translation_id'), table_name='blog_category_translation')
    op.drop_index(op.f('ix_blog_category_translation_category_id'), table_name='blog_category_translation')
    op.drop_table('blog_category_translation')
    op.drop_index(op.f('ix_author_slug'), table_name='author')
    op.drop_index(op.f('ix_author_id'), table_name='author')
    op.drop_index(op.f('ix_author_deleted_at'), table_name='author')
    op.drop_table('author')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_setting_translation_setting_id'), table_name='setting_translation')
    op.drop_index(op.f('ix_setting_translation_locale'), table_name='setting_translation')
    op.drop_index(op.f('ix_setting_translation_id'), table_name='setting_translation')
    op.drop_table('setting_translation')
    op.drop_index(op.f('ix_page_status'), table_name='page')
    op.drop_index(op.f('ix_page_sort_order'), table_name='page')
    op.drop_index(op.f('ix_page_slug'), table_name='page')
    op.drop_index(op.f('ix_page_published_at'), table_name='page')
    op.drop_index(op.f('ix_page_is_published'), table_name='page')
    op.drop_index(op.f('ix_page_id'), table_name='page')
    op.drop_index(op.f('ix_page_deleted_at'), table_name='page')
    op.drop_table('page')
    op.drop_index(op.f('ix_packing_item_translation_packing_item_id'), table_name='packing_item_translation')
    op.drop_index(op.f('ix_packing_item_translation_locale'), table_name='packing_item_translation')
    op.drop_index(op.f('ix_packing_item_translation_id'), table_name='packing_item_translation')
    op.drop_table('packing_item_translation')
    op.drop_index(op.f('ix_media_translation_media_id'), table_name='media_translation')
    op.drop_index(op.f('ix_media_translation_locale'), table_name='media_translation')
    op.drop_index(op.f('ix_media_translation_id'), table_name='media_translation')
    op.drop_table('media_translation')
    op.drop_index(op.f('ix_inclusion_translation_locale'), table_name='inclusion_translation')
    op.drop_index(op.f('ix_inclusion_translation_inclusion_id'), table_name='inclusion_translation')
    op.drop_index(op.f('ix_inclusion_translation_id'), table_name='inclusion_translation')
    op.drop_table('inclusion_translation')
    op.drop_index(op.f('ix_highlight_translation_locale'), table_name='highlight_translation')
    op.drop_index(op.f('ix_highlight_translation_id'), table_name='highlight_translation')
    op.drop_index(op.f('ix_highlight_translation_highlight_id'), table_name='highlight_translation')
    op.drop_table('highlight_translation')
    op.drop_index(op.f('ix_gallery_sort_order'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_slug'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_published_at'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_is_published'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_id'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_deleted_at'), table_name='gallery')
    op.drop_table('gallery')
    op.drop_index(op.f('ix_destination_sort_order'), table_name='destination')
    op.drop_index(op.f('ix_destination_slug'), table_name='destination')
    op.drop_index(op.f('ix_destination_published_at'), table_name='destination')
    op.drop_index(op.f('ix_destination_parent_id'), table_name='destination')
    op.drop_index(op.f('ix_destination_is_published'), table_name='destination')
    op.drop_index(op.f('ix_destination_id'), table_name='destination')
    op.drop_index(op.f('ix_destination_deleted_at'), table_name='destination')
    op.drop_index(op.f('ix_destination_code'), table_name='destination')
    op.drop_table('destination')
    op.drop_index(op.f('ix_blog_category_sort_order'), table_name='blog_category')
    op.drop_index(op.f('ix_blog_category_slug'), table_name='blog_category')
    op.drop_index(op.f('ix_blog_category_published_at'), table_name='blog_category')
    op.drop_index(op.f('ix_blog_category_is_published'), table_name='blog_category')
    op.drop_index(op.f('ix_blog_category_id'), table_name='blog_category')
    op.drop_index(op.f('ix_blog_category_deleted_at'), table_name='blog_category')
    op.drop_index(op.f('ix_blog_category_code'), table_name='blog_category')
    op.drop_table('blog_category')
    op.drop_index(op.f('ix_admin_user_role'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_is_active'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_id'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_email'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_deleted_at'), table_name='admin_user')
    op.drop_table('admin_user')
    op.drop_index(op.f('ix_setting_key'), table_name='setting')
    op.drop_index(op.f('ix_setting_id'), table_name='setting')
    op.drop_index(op.f('ix_setting_group'), table_name='setting')
    op.drop_table('setting')
    op.drop_index(op.f('ix_redirect_is_active'), table_name='redirect')
    op.drop_index(op.f('ix_redirect_id'), table_name='redirect')
    op.drop_index(op.f('ix_redirect_from_path'), table_name='redirect')
    op.drop_table('redirect')
    op.drop_index(op.f('ix_packing_item_id'), table_name='packing_item')
    op.drop_index(op.f('ix_packing_item_deleted_at'), table_name='packing_item')
    op.drop_index(op.f('ix_packing_item_code'), table_name='packing_item')
    op.drop_table('packing_item')
    op.drop_index(op.f('ix_media_kind'), table_name='media')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_index(op.f('ix_media_folder'), table_name='media')
    op.drop_index(op.f('ix_media_deleted_at'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_inclusion_id'), table_name='inclusion')
    op.drop_index(op.f('ix_inclusion_deleted_at'), table_name='inclusion')
    op.drop_index(op.f('ix_inclusion_code'), table_name='inclusion')
    op.drop_table('inclusion')
    op.drop_index(op.f('ix_highlight_id'), table_name='highlight')
    op.drop_index(op.f('ix_highlight_deleted_at'), table_name='highlight')
    op.drop_index(op.f('ix_highlight_code'), table_name='highlight')
    op.drop_table('highlight')
    # ### end Alembic commands ###
