"""add itinerary step details: hotel, distance, location, meal plan

Revision ID: cefd48e9696f
Revises: 9c987320cf76
Create Date: 2026-08-16 16:44:29.005803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cefd48e9696f'
down_revision: Union[str, Sequence[str], None] = '9c987320cf76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_itinerary_item', sa.Column('hotel_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('product_itinerary_item', sa.Column('distance_km', sa.Integer(), nullable=True))
    op.add_column('product_itinerary_translation', sa.Column('location_label', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('product_itinerary_translation', sa.Column('meal_plan', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_itinerary_translation', 'meal_plan')
    op.drop_column('product_itinerary_translation', 'location_label')
    op.drop_column('product_itinerary_item', 'distance_km')
    op.drop_column('product_itinerary_item', 'hotel_name')
    # ### end Alembic commands ###
